#pragma once
#include <pgmspace.h>
const char CONTROL_PAGE[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TV UART control</title><style>
:root{color-scheme:dark;font:16px system-ui;background:#121820;color:#edf2f7}body{max-width:880px;margin:auto;padding:24px}h1{font-size:26px}h2{font-size:20px}section{background:#1b2633;border:1px solid #354457;border-radius:12px;padding:20px;margin:16px 0}input,textarea,button{font:inherit;border-radius:6px;border:1px solid #53667a;background:#111b26;color:inherit;padding:9px}button{cursor:pointer;background:#2d4863}button:disabled{opacity:.45;cursor:default}.danger{background:#8b3030}.safe{background:#285740}label{display:block;margin:12px 0}input[type=number]{width:100px}input[type=password]{width:min(90%,520px)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.buttons{display:flex;gap:10px;flex-wrap:wrap}.warn{border-left:4px solid #e9ad62;padding:10px;background:#35291e}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #354457}td input.command{width:95%;box-sizing:border-box}td input.wait{width:86px}pre{white-space:pre-wrap;max-height:240px;overflow:auto}#error{color:#ffb5a9;white-space:pre-wrap}#state{font-size:20px;font-weight:600}small,.muted{color:#b1c1d1}a{color:#9ed0ff}@media(max-width:600px){body{padding:12px}.grid{grid-template-columns:1fr}th,td{padding:4px}td input.wait{width:65px}}
</style></head><body><h1>TV UART control</h1>
<p>GPIO25 RX · GPIO26 TX · 115200 baud. One sequence per ARM. No automatic repeat.</p>
<section id="login"><h2>Connect</h2><label>Bridge access key <input id="key" type="password" autocomplete="off"></label><button id="connect">Connect</button><p class="muted">The access key stays in this browser tab. No outside services are used.</p></section>
<p id="error" role="alert"></p>
<main id="control" hidden>
<section><div id="state" role="status">Connecting…</div><p id="progress"></p><p><b>ARM next ESP startup:</b> power cycling the ESP starts this sequence once and immediately clears the ARM flag. A TV restart alone does not trigger an independently powered ESP.</p><p><b>Start now:</b> starts the timeline immediately. With separate ESP power, start an Enter burst and restart the TV during that burst.</p><div class="buttons"><button class="safe" id="dry">Dry run · no UART transmission</button><button id="now">Start now</button><button id="arm">ARM next ESP startup</button><button class="danger" id="stop">DISARM / STOP</button></div><p class="muted">STOP cancels future transmissions. It cannot undo commands already sent.</p></section>
<section><h2>Timing</h2><div class="grid"><label>Wait before Enter (ms) <input id="start" type="number" min="0" max="120000" value="0"></label><label>Enter burst duration (ms) <input id="enter" type="number" min="0" max="120000" value="10000"></label><label>Enter interval (ms) <input id="interval" type="number" min="20" max="1000" value="100"></label><label>Quiet time after Enter (ms) <input id="settle" type="number" min="0" max="30000" value="2000"></label></div><p class="muted">Starting values: 10 seconds of Enter every 100 ms, then 2 seconds of quiet. These are adjustable estimates; verify the boot prompt and adapt timing to your device.</p><h2>Commands</h2><p>Each command ends with Enter. “Wait after” runs after that command, including the last step.</p><table><thead><tr><th>Command</th><th>Wait after (ms)</th><th></th></tr></thead><tbody id="steps"></tbody></table><div class="buttons" style="margin-top:12px"><button id="add">Add command</button><button id="diagnostic">Load version check</button><button class="danger" id="unlock">Load unlock sequence</button><button id="save">Save settings</button></div><p id="timeline"></p><div class="warn"><b>Unlock commands can factory-reset the TV and erase apps, accounts, and settings.</b> Run destructive commands only after verifying the target, image, slot and recovery path. A transmit log is not proof that the TV executed a command.</div><label><input id="risk" type="checkbox"> I understand that running these commands can erase my TV setup.</label></section>
<section><h2>Transmission timeline</h2><pre id="events">No run yet.</pre><p class="muted">This records planned events and bytes sent by the ESP. It does not read or interpret the TV console.</p></section>
<section><h2>ESP firmware update over Wi-Fi</h2><p>Choose a firmware.bin built for this bridge. Updating automatically DISARMs and stops the sequence. After the reboot it remains disarmed.</p><input id="firmware" type="file" accept=".bin"><button id="update">Install firmware</button></section>
</main><script>
let token=sessionStorage.getItem('tclKey')||'',online=false,busy=false,current=null,dirty=false;
const $=id=>document.getElementById(id);
const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('key')){token=hash.get('key');sessionStorage.setItem('tclKey',token);history.replaceState(null,'',location.pathname);}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token},body,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json();}
function row(command='',wait=2000){if($('steps').children.length>=12)return;const tr=document.createElement('tr');const c=document.createElement('input');c.className='command';c.maxLength=256;c.value=command;c.setAttribute('aria-label','Command');const w=document.createElement('input');w.className='wait';w.type='number';w.min=0;w.max=60000;w.value=wait;w.setAttribute('aria-label','Wait after command in milliseconds');const b=document.createElement('button');b.textContent='×';b.setAttribute('aria-label','Remove command');b.onclick=()=>{tr.remove();changed()};for(const el of [c,w,b]){const td=document.createElement('td');td.append(el);tr.append(td)}c.oninput=w.oninput=changed;$('steps').append(tr);}
function profile(){return {start:+$('start').value,enter:+$('enter').value,interval:+$('interval').value,settle:+$('settle').value,steps:[...$('steps').children].map(tr=>({command:tr.querySelector('.command').value,wait:+tr.querySelector('.wait').value}))};}
function showProfile(p){$('start').value=p.start;$('enter').value=p.enter;$('interval').value=p.interval;$('settle').value=p.settle;$('steps').replaceChildren();p.steps.forEach(s=>row(s.command,s.wait));dirty=false;timeline();}
function changed(){dirty=true;$('risk').checked=false;timeline();}
function timeline(){const p=profile();let ms=p.start+p.enter+p.settle;let lines=[`First command at approximately ${(ms/1000).toFixed(1)} s.`];p.steps.forEach((s,i)=>{lines.push(`${i+1}: ${(ms/1000).toFixed(1)} s`);ms+=s.wait});$('timeline').textContent=lines.join(' · ')+` · Finished at approximately ${(ms/1000).toFixed(1)} s.`;}
function form(){const p=profile(),f=new URLSearchParams;for(const k of ['start','enter','interval','settle'])f.set(k,p[k]);f.set('count',p.steps.length);p.steps.forEach((s,i)=>{f.set('cmd'+i,s.command);f.set('wait'+i,s.wait)});return f;}
function controls(){const running=current&&current.active,armed=current&&current.armed,locked=busy||!online||running||armed;$('arm').disabled=$('now').disabled=locked;$('dry').disabled=$('save').disabled=locked;$('stop').disabled=busy||!online;for(const el of document.querySelectorAll('#steps input,#steps button,#start,#enter,#interval,#settle,#add,#diagnostic,#unlock'))el.disabled=locked;$('update').disabled=busy||!online;}
async function refresh(load=false){const s=await api('/automation');current=s;online=true;$('state').textContent=(s.armed?'ARMED — next ESP startup':s.active?(s.dry_run?'DRY RUN — ':'RUNNING — ')+s.phase:s.phase==='complete'?'Completed · disarmed':s.phase==='stopped'?'Stopped · disarmed':'DISARMED');$('progress').textContent=`Enter events: ${s.enter_count} · Commands ${s.commands_sent}/${s.profile.steps.length} · Elapsed ${(s.elapsed_ms/1000).toFixed(1)} s`;if(load)showProfile(s.profile);$('events').textContent=s.events.map(e=>`${(e.ms/1000).toFixed(3)} s ${s.dry_run?'[dry run] ':''}${e.name}${e.step>=0?' · '+s.profile.steps[e.step].command:''}`).join('\n')||'No run yet.';controls();}
async function action(fn){busy=true;controls();$('error').textContent='';try{await fn();await refresh();}catch(e){$('error').textContent=e.message;}finally{busy=false;controls();}}
$('connect').onclick=()=>action(async()=>{token=$('key').value||token;await refresh(true);sessionStorage.setItem('tclKey',token);$('login').hidden=true;$('control').hidden=false;});
$('save').onclick=()=>action(async()=>{await api('/automation/config',form());dirty=false;});
async function start(mode){const f=form();f.set('mode',mode);if(mode!=='dry'){const changes=profile().steps.some(s=>! /^(version|help(?: .*)?|printenv(?: .*)?|coninfo)$/.test(s.command.trim()));if(changes&&!$('risk').checked){if(!confirm('This sequence can change the TV firmware. Unlock commands can FACTORY-RESET the TV and erase apps, accounts, and settings. Continue?'))return;$('risk').checked=true;}f.set('risk','ack');}await api('/automation/start',f);dirty=false;}
$('dry').onclick=()=>action(()=>start('dry'));
$('now').onclick=()=>action(()=>start('now'));
$('arm').onclick=()=>action(()=>start('arm'));
$('stop').onclick=()=>action(()=>api('/automation/disarm',new URLSearchParams('stop=1')));
$('add').onclick=()=>{row();changed()};
$('diagnostic').onclick=()=>{showProfile({start:0,enter:10000,interval:100,settle:2000,steps:[{command:'version',wait:2000}]});changed()};
$('unlock').onclick=()=>{showProfile({start:0,enter:10000,interval:100,settle:2000,steps:[...['env set devicestate unlock','avb init mmc','avb set-devicestate 0','avb set-verity disable'].map(command=>({command,wait:2000})),{command:'saveenv',wait:5000},{command:'reset',wait:2000}]});changed()};
for(const id of ['start','enter','interval','settle'])$(id).oninput=changed;$('risk').onchange=controls;
$('update').onclick=()=>action(async()=>{const file=$('firmware').files[0];if(!file)throw new Error('Choose firmware.bin first.');if(!confirm('Stop and disarm the sequence, update the ESP firmware, and restart it?'))return;const f=new FormData;f.set('firmware',file);await api('/update',f);online=false;throw new Error('Firmware installed. ESP is restarting; reconnect in about 15 seconds.');});
setInterval(async()=>{if(!token||busy)return;try{await refresh()}catch(e){online=false;controls();$('error').textContent='Bridge unreachable: '+e.message}},1000);
if(token)$('connect').click();
</script></body></html>)HTML";
